name: Job output Demo
on:
  push:
    branches:
      - main
    paths:
        - '.github/workflows/first-workflow.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version}}

    steps:
      - name: SET Version
        id: set_version
        run: echo "version=1.0.${{github.run_number}}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use version
        run: echo "Deploying version ${{needs.build.outputs.version}}"

      - name: Print GitHub Context Info
        run: |
         echo "Repository: ${{ github.repository }}"
         echo "Actor: ${{ github.actor }}"
         echo "Commit SHA: ${{ github.sha }}"
         echo "Branch Ref: ${{ github.ref }}"
         echo "Run ID: ${{ github.run_id }}"
         echo "Run Number: ${{ github.run_number }}"