
name: My first workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: show files
        run: ls -la
      #  run: echo "Hi There, GitHub Actions is working"

