name: Matrix Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Print Node Version
        run: echo "Running on Node ${{ matrix.node-version }}"