name: reusable build workflow
on:
  workflow_call:
    inputs:
      app_name:
         required: true
         type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build application
        run: echo "Building ${{inputs.app_name}}"
